debug: true
logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug
wx:
  miniapp:
    configs:
        - appid: wx77856a389b827dee
          secret: f6cc28ce661594bdfd7e46e2a24f6742
          token: whwsxx2019
          aesKey: APJVp5WTr0pRVWurtWOGMBFXkifMa2ZNUixPoV6Qx4T
          msgDataFormat: JSON

spring:
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/invite
        username: root
        password: whws2019
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
